import { describe, it, expect } from "vitest";
import { runDemo } from "../src/demo.js";

describe("demo-offline runner", () => {
  it("walks the Golden Thread to completion and returns 0", async () => {
    const out: string[] = [];
    const code = await runDemo((s) => out.push(s));
    expect(code).toBe(0);
    const text = out.join("\n");
    // S128: the creative-arc headline leads the demo (Battle Arena -> ScoreCard).
    expect(text).toContain("BATTLE MODE ARENA");
    expect(text).toContain("creative front door");
    expect(text).toMatch(/SCORECARD: Acme Support Bot defended \d+\/\d+/);
    expect(text).toContain("Compile graph");
    expect(text).toContain("Remove-the-source");
    expect(text).toContain("DEFENDED");
    expect(text).toContain("outcome=approved");
    expect(text).toContain("roundTripLossless=true");
    expect(text).toContain("state=deployed");
    expect(text).toContain("regressed=false");
    expect(text).toContain("budget verdict=ok");
    expect(text).toContain("tier=gold");
    expect(text).toContain("published pack-acme");
    expect(text).toContain("interoperable");
    expect(text).toContain("Governance report");
    expect(text).toContain("cross-tenant blocked=true");
    expect(text).toContain("tamper detected at seq=1");
    expect(text).toContain("malicious caught=true");
    expect(text).toContain("notifications sent=3");
    expect(text).toContain("connector resolves plaintext");
    expect(text).toContain("eval p99=34ms");
    expect(text).toContain("residency (us) blocked=true");
    expect(text).toContain("no real side effects");
    expect(text).toContain("signed delivery");
    expect(text).toContain("POST /agents -> 201");
    expect(text).toContain("policy 'high-risk'");
    expect(text).toContain("throttled");
    expect(text).toContain("rolled back to approved");
    expect(text).toContain("runtime-redteam");
    expect(text).toContain("hash-chained");
    expect(text).toContain("policy gate blocks");
    expect(text).toContain("documented paths");
    expect(text).toContain("expired token -> rejected");
    expect(text).toContain("over socket");
    expect(text).toContain("user JIT-provisioned");
    expect(text).toContain("invalid body -> false");
    expect(text).toContain("line items, total");
    expect(text).toContain("schema error(s)");
    expect(text).toContain("usage_spike/critical");
    expect(text).toContain("lifetime");
    expect(text).toContain("on-call notified");
    expect(text).toContain("scheduled close ran");
    expect(text).toContain("failed over to replica");
    expect(text).toContain("drift vs approved baseline");
    expect(text).toContain("component(s) probed");
    expect(text).toContain("onboarded 'newco'");
    expect(text).toContain("drift scan ran");
    expect(text).toContain("status: degraded");
    expect(text).toContain("restored 2 into fresh store");
    expect(text).toContain("GET /status -> 200");
    expect(text).toContain("vault retains 3");
    expect(text).toContain("platform.recovered");
    expect(text).toContain("backup drill: passed=true");
    expect(text).toContain("vs target 99.9%");
    expect(text).toContain("signed; verify=true");
    expect(text).toContain("GET /audit/export -> 200");
    expect(text).toContain("1 breach(es)");
    expect(text).toContain("readiness=ready");
    expect(text).toContain("rolled back to v1 config as v3");
    expect(text).toContain("compliance pack: 4 sections");
    expect(text).toContain("GET /dr/runbook -> 200");
    expect(text).toContain("profile v1->v2: 5 change(s)");
    expect(text).toContain("applied profile v3 to live subsystems");
    expect(text).toContain("GET /compliance/pack -> 200");
    expect(text).toContain("1 drift [quotaLimits]");
    expect(text).toContain("profile.applied recorded");
    expect(text).toContain("POST /profiles/t1/apply -> 200");
    expect(text).toContain("1 auto-remediated");
    expect(text).toContain("applied [quotas, retention, sla] + recorded");
    expect(text).toContain("GET /profiles/t1/history -> 200");
    expect(text).toContain("drifted from config profile");
    expect(text).toContain("imported to prod-tenant as v1");
    expect(text).toContain("archive retains 3");
    expect(text).toContain("POST /import -> 200");
    expect(text).toContain("trend=improving");
    expect(text).toContain("posture diff: 3 change(s)");
    expect(text).toContain("recorded 3 samples on a schedule");
    expect(text).toContain("GET /status/history -> 200");
    expect(text).toContain("GET /compliance/history -> 200");
    expect(text).toContain("no network used");
  });

  it("shows grounded-accuracy dropping when Foundry IQ is toggled off", async () => {
    const out: string[] = [];
    await runDemo((s) => out.push(s));
    const text = out.join("\n");
    // remove-the-source line reports a drop to 0.000
    expect(text).toMatch(/drops 1\.000 -> 0\.000/);
  });
});
